export type Team = {
  team_id: number
  name: string
  abbr: string
  nickname: string
  logo_file_name: string
  city_id: number
  park_id: number
  league_id: number
  sub_league_id: number
  division_id: number
  nation_id: number
  parent_team_id: number
  level: number
  prevent_any_moves: number
  human_team: number
  human_id: number
  gender: number
  background_color_id: string
  text_color_id: string
  ballcaps_main_color_id: string
  ballcaps_visor_color_id: string
  jersey_main_color_id: string
  jersey_away_color_id: string
  jersey_secondary_color_id: string
  jersey_pin_stripes_color_id: string
  allstar_team: number
  historical_id: string
}

export type Player = {
  player_id: number
  team_id: number
  league_id: number
  position: number
  role: number
  first_name: string
  last_name: string
  nick_name: string
  age: number
  date_of_birth: string
  city_of_birth_id: number
  nation_id: number
  second_nation_id: number
  weight: number
  height: number
  retired: number
  free_agent: number
  last_league_id: number
  last_team_id: number
  organization_id: number
  last_organization_id: number
  language_ids0: number
  language_ids1: number
  uniform_number: number
  experience: number
  person_type: number
  bats: number
  throws: number
  personality_greed: number
  personality_loyalty: number
  personality_play_for_winner: number
  personality_work_ethic: number
  personality_intelligence: number
  personality_leader: number
  historical_id: string
  historical_team_id: string
  best_contract_offer_id: number
  injury_is_injured: number
  injury_dtd_injury: number
  injury_career_ending: number
  injury_dl_left: number
  injury_dl_playoff_round: number
  injury_left: number
  dtd_injury_effect: number
  dtd_injury_effect_hit: number
  dtd_injury_effect_throw: number
  dtd_injury_effect_run: number
  injury_id: number
  injury_id2: number
  injury_dtd_injury2: number
  injury_left2: number
  dtd_injury_effect2: number
  dtd_injury_effect_hit2: number
  dtd_injury_effect_throw2: number
  dtd_injury_effect_run2: number
  prone_overall: number
  prone_leg: number
  prone_back: number
  prone_arm: number
  fatigue_pitches0: number
  fatigue_pitches1: number
  fatigue_pitches2: number
  fatigue_pitches3: number
  fatigue_pitches4: number
  fatigue_pitches5: number
  fatigue_points: number
  fatigue_played_today: number
  running_ratings_speed: number
  running_ratings_stealing: number
  running_ratings_baserunning: number
  college: string
  acquired: number
  acquired_date: string
  draft_year: number
  draft_round: number
  draft_supplemental: number
  draft_pick: number
  draft_overall_pick: number
  draft_eligible: number
  hsc_status: number
  redshirt: number
  picked_in_draft: number
  school: string
  commit_school: string
  hidden: number
  draft_league_id: number
  draft_team_id: number
  turned_coach: number
  hall_of_fame: number
  rust: number
  inducted: number
  strategy_override_team: number
  strategy_stealing: number
  strategy_running: number
  strategy_bunt_for_hit: number
  strategy_sac_bunt: number
  strategy_hit_run: number
  strategy_hook_start: number
  strategy_hook_relief: number
  strategy_pitch_count: number
  strategy_pitch_around: number
  strategy_never_pinch_hit: number
  strategy_defensive_sub: number
  strategy_dtd_sit_min: number
  strategy_dtd_allow_ph: number
  local_pop: number
  national_pop: number
  draft_protected: number
  morale: number
  morale_player_performance: number
  morale_team_performance: number
  morale_team_transactions: number
  expectation: number
  morale_player_role: number
  on_loan: number
  loan_league_id: number
  loan_team_id: number
}

export type PlayerBatting = {
  player_id: number
  team_id: number
  league_id: number
  position: number
  role: number
  batting_ratings_overall_contact: number
  batting_ratings_overall_gap: number
  batting_ratings_overall_eye: number
  batting_ratings_overall_strikeouts: number
  batting_ratings_overall_hp: number
  batting_ratings_overall_power: number
  batting_ratings_overall_babip: number
  batting_ratings_vsr_contact: number
  batting_ratings_vsr_gap: number
  batting_ratings_vsr_eye: number
  batting_ratings_vsr_strikeouts: number
  batting_ratings_vsr_hp: number
  batting_ratings_vsr_power: number
  batting_ratings_vsr_babip: number
  batting_ratings_vsl_contact: number
  batting_ratings_vsl_gap: number
  batting_ratings_vsl_eye: number
  batting_ratings_vsl_strikeouts: number
  batting_ratings_vsl_hp: number
  batting_ratings_vsl_power: number
  batting_ratings_vsl_babip: number
  batting_ratings_talent_contact: number
  batting_ratings_talent_gap: number
  batting_ratings_talent_eye: number
  batting_ratings_talent_strikeouts: number
  batting_ratings_talent_hp: number
  batting_ratings_talent_power: number
  batting_ratings_talent_babip: number
  batting_ratings_misc_bunt: number
  batting_ratings_misc_bunt_for_hit: number
  batting_ratings_misc_gb_hitter_type: number
  batting_ratings_misc_fb_hitter_type: number
}

export type PlayerFielding = {
  player_id: number
  team_id: number
  league_id: number
  position: number
  role: number
  fielding_ratings_infield_range: number
  fielding_ratings_infield_arm: number
  fielding_ratings_turn_doubleplay: number
  fielding_ratings_outfield_range: number
  fielding_ratings_outfield_arm: number
  fielding_ratings_catcher_arm: number
  fielding_ratings_catcher_ability: number
  fielding_ratings_infield_error: number
  fielding_ratings_outfield_error: number
  fielding_experience0: number
  fielding_experience1: number
  fielding_experience2: number
  fielding_experience3: number
  fielding_experience4: number
  fielding_experience5: number
  fielding_experience6: number
  fielding_experience7: number
  fielding_experience8: number
  fielding_experience9: number
  fielding_rating_pos1: number
  fielding_rating_pos2: number
  fielding_rating_pos3: number
  fielding_rating_pos4: number
  fielding_rating_pos5: number
  fielding_rating_pos6: number
  fielding_rating_pos7: number
  fielding_rating_pos8: number
  fielding_rating_pos9: number
}

export type PlayerPitching = {
  player_id: number
  team_id: number
  league_id: number
  position: number
  role: number
  pitching_ratings_overall_stuff: number
  pitching_ratings_overall_control: number
  pitching_ratings_overall_movement: number
  pitching_ratings_overall_balk: number
  pitching_ratings_overall_hp: number
  pitching_ratings_overall_wild_pitch: number
  pitching_ratings_vsr_stuff: number
  pitching_ratings_vsr_control: number
  pitching_ratings_vsr_movement: number
  pitching_ratings_vsr_balk: number
  pitching_ratings_vsr_hp: number
  pitching_ratings_vsr_wild_pitch: number
  pitching_ratings_vsl_stuff: number
  pitching_ratings_vsl_control: number
  pitching_ratings_vsl_movement: number
  pitching_ratings_vsl_balk: number
  pitching_ratings_vsl_hp: number
  pitching_ratings_vsl_wild_pitch: number
  pitching_ratings_talent_stuff: number
  pitching_ratings_talent_control: number
  pitching_ratings_talent_movement: number
  pitching_ratings_talent_balk: number
  pitching_ratings_talent_hp: number
  pitching_ratings_talent_wild_pitch: number
  pitching_ratings_pitches_fastball: number
  pitching_ratings_pitches_slider: number
  pitching_ratings_pitches_curveball: number
  pitching_ratings_pitches_screwball: number
  pitching_ratings_pitches_forkball: number
  pitching_ratings_pitches_changeup: number
  pitching_ratings_pitches_sinker: number
  pitching_ratings_pitches_splitter: number
  pitching_ratings_pitches_knuckleball: number
  pitching_ratings_pitches_cutter: number
  pitching_ratings_pitches_circlechange: number
  pitching_ratings_pitches_knucklecurve: number
  pitching_ratings_pitches_talent_fastball: number
  pitching_ratings_pitches_talent_slider: number
  pitching_ratings_pitches_talent_curveball: number
  pitching_ratings_pitches_talent_screwball: number
  pitching_ratings_pitches_talent_forkball: number
  pitching_ratings_pitches_talent_changeup: number
  pitching_ratings_pitches_talent_sinker: number
  pitching_ratings_pitches_talent_splitter: number
  pitching_ratings_pitches_talent_knuckleball: number
  pitching_ratings_pitches_talent_cutter: number
  pitching_ratings_pitches_talent_circlechange: number
  pitching_ratings_pitches_talent_knucklecurve: number
  pitching_ratings_misc_velocity: number
  pitching_ratings_misc_arm_slot: number
  pitching_ratings_misc_stamina: number
  pitching_ratings_misc_ground_fly: number
  pitching_ratings_misc_hold: number
  pitching_ratings_babip: number
}

export type PlayerCareerBattingStats = {
  player_id: number
  year: number
  team_id: number
  game_id: number
  league_id: number
  level_id: number
  split_id: number
  position: number
  ab: number
  h: number
  k: number
  pa: number
  pitches_seen: number
  g: number
  gs: number
  d: number
  t: number
  hr: number
  r: number
  rbi: number
  sb: number
  cs: number
  bb: number
  ibb: number
  gdp: number
  sh: number
  sf: number
  hp: number
  ci: number
  wpa: number
  stint: number
  ubr: number
  war: number
}

export type PlayerCareerFieldingStats = {
  player_id: number
  year: number
  team_id: number
  league_id: number
  level_id: number
  split_id: number
  position: number
  tc: number
  a: number
  po: number
  er: number
  ip: number
  g: number
  gs: number
  e: number
  dp: number
  tp: number
  pb: number
  sba: number
  rto: number
  ipf: number
  plays: number
  plays_base: number
  roe: number
  opps_0: number
  opps_made_0: number
  opps_1: number
  opps_made_1: number
  opps_2: number
  opps_made_2: number
  opps_3: number
  opps_made_3: number
  opps_4: number
  opps_made_4: number
  opps_5: number
  opps_made_5: number
  framing: number
  arm: number
  zr: number
}

export type PlayerCareerPitchingStats = {
  player_id: number
  year: number
  team_id: number
  game_id: number
  league_id: number
  level_id: number
  split_id: number
  ip: number
  ab: number
  tb: number
  ha: number
  k: number
  bf: number
  rs: number
  bb: number
  r: number
  er: number
  gb: number
  fb: number
  pi: number
  ipf: number
  g: number
  gs: number
  w: number
  l: number
  s: number
  sa: number
  da: number
  sh: number
  sf: number
  ta: number
  hra: number
  bk: number
  ci: number
  iw: number
  wp: number
  hp: number
  gf: number
  dp: number
  qs: number
  svo: number
  bs: number
  ra: number
  cg: number
  sho: number
  sb: number
  cs: number
  hld: number
  ir: number
  irs: number
  wpa: number
  li: number
  stint: number
  outs: number
  sd: number
  md: number
  war: number
  ra9war: number
}
